frr version 7.0
frr defaults traditional
hostname devstack
log file /var/log/frr/frr.log debugging
log timestamp precision 3
service integrated-vtysh-config
line vty
debug bfd peer
debug bfd network
debug bfd zebra
debug bgp graceful-restart
debug bgp neighbor-events
debug bgp updates
debug bgp update-groups

vrf ovnvrf10
 ip protocol bgp route-map rm-install-only-default
exit-vrf

router bgp 64999 vrf ovnvrf10
 address-family ipv4 unicast
  ! Leak everything from root (including dynamic next-hops)
  import vrf default
 exit-address-family
exit

router bgp 64999 vrf ovnvrf42
  bgp log-neighbor-changes
  no bgp default ipv4-unicast
  no bgp ebgp-requires-policy

  address-family ipv4 unicast
    redistribute kernel
  exit-address-family

router bgp 64999
  bgp router-id 172.24.4.1
  bgp log-neighbor-changes
  bgp graceful-shutdown
  no bgp default ipv4-unicast
  no bgp ebgp-requires-policy

  neighbor uplink peer-group
  neighbor uplink remote-as internal
  neighbor uplink password f00barZ
  neighbor br-bgp-0 interface peer-group uplink
  neighbor br-bgp-1 interface peer-group uplink
  neighbor uplink bfd
  neighbor uplink bfd profile devstack

  address-family ipv4 unicast
    import vrf ovnvrf42
    redistribute connected
    neighbor uplink activate
    neighbor uplink allowas-in origin
    neighbor uplink prefix-list only-host-prefixes out
  exit-address-family

  address-family ipv6 unicast
    redistribute connected
    neighbor uplink activate
    neighbor uplink allowas-in origin
    neighbor uplink prefix-list only-host-prefixes out
  exit-address-family

ip prefix-list only-default permit 0.0.0.0/0
ip prefix-list only-host-prefixes permit 0.0.0.0/0 ge 32

route-map rm-only-default permit 10
  match ip address prefix-list only-default
  set src 172.24.4.1

ip protocol bgp route-map rm-only-default

ipv6 prefix-list only-default permit ::/0
ipv6 prefix-list only-host-prefixes permit ::/0 ge 128

route-map rm-only-default permit 11
  match ipv6 address prefix-list only-default
  set src 2001:db8::2

route-map rm-install-only-default permit 10
  match ip address prefix-list only-default

ipv6 protocol bgp route-map rm-only-default

ip nht resolve-via-default

bfd
  profile devstack
    detect-multiplier 10
    transmit-interval 500
    receive-interval 500
