- job:
    name: neutron-functional
    parent: devstack-minimal
    description: Run neutron functional tests
    timeout: 7800
    required-projects:
      - opendev.org/openstack/devstack
      - openstack/neutron
      - openstack/requirements
    roles:
      - zuul: openstack/devstack
    pre-run: playbooks/configure_functional_job.yaml
    run: playbooks/run_functional_job.yaml
    post-run: playbooks/post_functional_job.yaml
    irrelevant-files: &irrelevant-files
      - ^\.pre-commit-config\.yaml$
      - ^\.pylintrc$
      - ^.*\.conf\.sample$
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^neutron/tests/fullstack/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^plugin.spec$
      - ^pyproject.toml$
      - ^tools/ovn_migration/.*$
      - ^vagrant/.*$
      - ^devstack/.*\.sample$
      - ^playbooks/add_mariadb_repo.yaml
      - ^playbooks/configure_ebtables.yaml
      - ^playbooks/dvr-multinode-scenario-pre-run.yaml
      - ^playbooks/install_nftables.yaml
      - ^playbooks/multinode-setup.yaml
      - ^playbooks/prepare-ovn-multinode.yaml
      - ^roles/add_mariadb_repo/.*$
      - ^roles/nftables/.*$
      - ^rally-jobs/.*$
      # Ignore everything except for zuul.d/project.yaml
      - ^zuul.d/base.yaml
      - ^zuul.d/grenade.yaml
      - ^zuul.d/job-templates.yaml
      - ^zuul.d/rally.yaml
      - ^zuul.d/tempest-multinode.yaml
      - ^zuul.d/tempest-singlenode.yaml
    vars:
      configure_swap_size: 8192
      Q_BUILD_OVS_FROM_GIT: True
      MEMORY_TRACKER: True
      INSTALL_OVN: True
      devstack_services:
        # Ignore any default set by devstack. Emit a "disable_all_services".
        base: false
        etcd3: false
      devstack_localrc:
        INSTALL_TESTONLY_PACKAGES: true
        DATABASE_PASSWORD: stackdb
        NEUTRON_DEPLOY_MOD_WSGI: true
      tox_envlist: dsvm-functional-gate
      tox_environment:
        PYTHONPATH: /opt/stack/data/venv/lib/python3.12/site-packages
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/openstack/requirements/upper-constraints.txt'
      zuul_copy_output:
        # We need to copy archive with logs to have it in job artifacts also,
        # /opt/stack/logs is default logs directory defined in neutron's
        # tox.ini file
        '/opt/stack/logs/dsvm-functional-logs.tar.gz': logs

- job:
    name: neutron-functional-with-neutron-lib-master
    branches: ^master$
    parent: neutron-functional
    required-projects:
      - openstack/neutron-lib

- job:
    name: neutron-functional-fips
    parent: neutron-functional
    nodeset: devstack-single-node-centos-9-stream
    description: |
      Functional testing for a FIPS enabled Centos 9 system
    vars:
      nslookup_target: 'opendev.org'
      enable_fips: True
      # NOTE(ykarel) remove python3 override with 10-stream switch
      PYTHON3_VERSION: 3.12
      tox_environment:
        TOX_PYTHON: python3.12
      devstack_localrc:
        ISCSI_CHAP_ALGORITHMS: SHA3-256,SHA256
        Q_BUILD_OVS_FROM_GIT: true

- job:
    name: neutron-functional-with-pyroute2-master
    branches: ^master$
    parent: neutron-functional
    required-projects:
      - name: github.com/svinota/pyroute2

- job:
    name: neutron-functional-with-oslo-master
    branches: ^master$
    parent: neutron-functional
    description: |
      This job installs all oslo libraries from source and executes the
      Neutron functional tests.
    # NOTE(ralonsoh): the list of required projects is retrieved from
    # "openstack-tox-with-oslo-master-base" job.
    # TODO(ralonsoh): push a patch to "openstack-zuul-jobs" to create
    # a list reference of the required projects for "-oslo-master" jobs.
    required-projects:
      - openstack/automaton
      - openstack/debtcollector
      - openstack/futurist
      - openstack/osprofiler
      - openstack/oslo.cache
      - openstack/oslo.concurrency
      - openstack/oslo.config
      - openstack/oslo.context
      - openstack/oslo.db
      - openstack/oslo.i18n
      - openstack/oslo.log
      - openstack/oslo.messaging
      - openstack/oslo.middleware
      - openstack/oslo.policy
      - openstack/oslo.privsep
      - openstack/oslo.reports
      - openstack/oslo.rootwrap
      - openstack/oslo.serialization
      - openstack/oslo.service
      - openstack/oslo.utils
      - openstack/oslo.versionedobjects
      - openstack/oslo.vmware
      - openstack/oslotest
      - openstack/pycadf
      - openstack/stevedore
      - openstack/taskflow
      - openstack/tooz
      - openstack/pbr

- job:
    name: neutron-functional-with-sqlalchemy-master
    branches: ^master$
    parent: neutron-functional
    required-projects:
      - name: github.com/sqlalchemy/sqlalchemy
        override-checkout: main
      - openstack/oslo.db
      - openstack/neutron-lib
      - name: github.com/sqlalchemy/alembic
        override-checkout: main

- job:
    name: openstack-tox-py312-with-sqlalchemy-master
    branches: ^master$
    parent: openstack-tox-py312
    required-projects:
      - name: github.com/sqlalchemy/sqlalchemy
        override-checkout: main
      - openstack/oslo.db
      - openstack/neutron-lib
      - name: github.com/sqlalchemy/alembic
        override-checkout: main

- job:
    name: neutron-ovs-tempest-plugin-iptables_hybrid-nftables
    parent: neutron-tempest-plugin-openvswitch-iptables_hybrid
    pre-run: playbooks/install_nftables.yaml
    vars:
      devstack_local_conf:
        post-config:
          $NEUTRON_CONF:
            SECURITYGROUP:
              enable_ipset: false  # Not compatible with nftables

# NOTE(ralonsoh): to be removed in 2026.2, once the OVN Metadata agent
# replacement finishes. See LP#2112313.
- job:
    name: neutron-tempest-plugin-ovn-with-ovn-metadata-agent
    parent: neutron-tempest-plugin-ovn
    vars:
      devstack_services:
        q-ovn-metadata-agent: true
        q-ovn-agent: false
