# NOTE: In doc/source/contributor/testing/ci_scenario_jobs.rst file there is
# document with summary of all tempest, neutron-tempest-plugin and grenade jobs
# summary.
# Please update this document always when any changes to jobs are made.
- project:
    templates:
      - neutron-tempest-plugin-jobs-victoria
      - openstack-cover-jobs
      - openstack-python3-victoria-jobs
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-functional-with-uwsgi:
            # We don't run the job on things like neutron docs-only changes
            irrelevant-files: &irrelevant-files
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
              - ^vagrant/.*$
              - ^migration/.*$
              - ^devstack/.*\.sample$
        - neutron-fullstack-with-uwsgi:
            irrelevant-files: *irrelevant-files
        - neutron-rally-task:
            irrelevant-files: *irrelevant-files
        - neutron-grenade-multinode:
            irrelevant-files: *irrelevant-files
        - neutron-grenade-dvr-multinode:
            irrelevant-files: *irrelevant-files
        - neutron-grenade-ovn:
            voting: false
            irrelevant-files: *irrelevant-files
        - neutron-tempest-linuxbridge:
            irrelevant-files: *irrelevant-files
        - neutron-tempest-with-uwsgi:
            irrelevant-files: *irrelevant-files
        - neutron-tempest-multinode-full-py3:
            irrelevant-files: *irrelevant-files
        - neutron-tempest-dvr-ha-multinode-full:
            irrelevant-files: *irrelevant-files
        - neutron-tempest-iptables_hybrid:
            irrelevant-files: *irrelevant-files
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa:
            voting: false
            irrelevant-files: *irrelevant-files
        - neutron-tempest-slow-py3:
            irrelevant-files: *irrelevant-files
        - neutron-tempest-ipv6-only:
            irrelevant-files: *irrelevant-files
        - neutron-ovn-tempest-ovs-release:
            irrelevant-files: *irrelevant-files
        - neutron-ovn-tempest-ovs-release-ipv6-only:
            voting: false
            irrelevant-files: *irrelevant-files
        # TODO(slaweq): add this job again to the check queue when it will be
        # working fine on python 3
        #- networking-midonet-tempest-aio-ml2-centos-7:
        #    voting: false
        #    irrelevant-files: *irrelevant-files
        - openstacksdk-functional-devstack-networking:
            voting: false
        - tripleo-ci-centos-8-content-provider:
            voting: false
            irrelevant-files: *irrelevant-files
        - neutron-centos-8-tripleo-standalone:
            vars: &consumer_vars
              consumer_job: true
              build_container_images: false
              remove_tags:
                - build
            dependencies: &consumer_deps
              - tripleo-ci-centos-8-content-provider
        - neutron-ovn-rally-task:
            voting: false
            irrelevant-files: *irrelevant-files
        # TripleO jobs that deploy OVN.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # In Stein and beyond, fs010 will run using
        # networking-ovn-tripleo-ci-centos-7-containers-multinode.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - neutron-ovn-tripleo-ci-centos-8-containers-multinode:
            voting: false
            vars: *consumer_vars
            dependencies: *consumer_deps
        - neutron-ovn-tempest-slow:
            voting: false
        - openstack-tox-py36:  # from openstack-python3-victoria-jobs template
            timeout: 3600
        - openstack-tox-py38:  # from openstack-python3-victoria-jobs template
            timeout: 3600
        - openstack-tox-cover:  # from openstack-cover-jobs template
            timeout: 4800
    gate:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-fullstack-with-uwsgi
        - neutron-tempest-with-uwsgi
        - neutron-tempest-linuxbridge
        - neutron-tempest-iptables_hybrid
        - neutron-tempest-multinode-full-py3
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode
        - neutron-tempest-slow-py3
        - neutron-tempest-ipv6-only
        - neutron-ovn-tempest-ovs-release
        - openstack-tox-py36:  # from openstack-python3-victoria-jobs template
            timeout: 3600
        #- neutron-ovn-rally-task
        #- neutron-ovn-tripleo-ci-centos-8-containers-multinode

    periodic:
      jobs:
        - neutron-functional
        - neutron-fullstack
        - neutron-tempest-postgres-full
        - neutron-tempest-mariadb-full
