# NOTE: In doc/source/contributor/testing/ci_scenario_jobs.rst file there is
# document with summary of all tempest, neutron-tempest-plugin and grenade jobs
# summary.
# Please update this document always when any changes to jobs are made.
- project:
    templates:
      - neutron-tempest-plugin-jobs-wallaby
      - openstack-cover-jobs
      - openstack-python3-wallaby-jobs
      - openstack-python3-wallaby-jobs-arm64
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
      - neutron-experimental-jobs
      - neutron-periodic-jobs
      - neutron-tox-override-jobs
    check:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode:
            # TODO(slaweq): make that job voting when bug
            # https://bugs.launchpad.net/neutron/+bug/1920778
            # will be fixed
            voting: false
        - neutron-tempest-multinode-full-py3
        - neutron-tempest-dvr-ha-multinode-full
        - neutron-tempest-slow-py3
        - neutron-tempest-ipv6-only
        - neutron-ovn-tempest-ovs-release
        - neutron-ovn-tempest-ovs-release-ipv6-only
        # TODO(slaweq): add this job again to the check queue when it will be
        # working fine on python 3
        #- networking-midonet-tempest-aio-ml2-centos-7:
        #    voting: false
        - neutron-ovn-tempest-slow
    gate:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-tempest-multinode-full-py3
        - neutron-grenade-multinode
        # TODO(slaweq): make that job gating when bug
        # https://bugs.launchpad.net/neutron/+bug/1920778
        # will be fixed
        # - neutron-grenade-dvr-multinode
        - neutron-tempest-slow-py3
        - neutron-tempest-ipv6-only
        - neutron-ovn-tempest-ovs-release
        - neutron-ovn-tempest-ovs-release-ipv6-only
        - neutron-ovn-tempest-slow
