# NOTE: In doc/source/contributor/testing/ci_scenario_jobs.rst file there is
# document with summary of all tempest, neutron-tempest-plugin and grenade jobs
# summary.
# Please update this document always when any changes to jobs are made.
- project:
    templates:
      - neutron-tempest-plugin-jobs-victoria
      - openstack-cover-jobs
      - openstack-python3-victoria-jobs
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode
        - neutron-grenade-ovn:
            voting: false
        - neutron-tempest-linuxbridge
        - neutron-tempest-with-uwsgi
        - neutron-tempest-multinode-full-py3
        - neutron-tempest-dvr-ha-multinode-full
        - neutron-tempest-iptables_hybrid
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa:
            voting: false
        - neutron-tempest-slow-py3
        - neutron-tempest-ipv6-only
        - neutron-ovn-tempest-ovs-release
        - neutron-ovn-tempest-ovs-release-ipv6-only:
            voting: false
        # TODO(slaweq): add this job again to the check queue when it will be
        # working fine on python 3
        #- networking-midonet-tempest-aio-ml2-centos-7:
        #    voting: false
        - openstacksdk-functional-devstack-networking:
            voting: false
        - neutron-ovn-tempest-slow:
            voting: false
        - openstack-tox-py36:  # from openstack-python3-victoria-jobs template
            timeout: 3600
        - openstack-tox-py38:  # from openstack-python3-victoria-jobs template
            timeout: 3600
        - openstack-tox-cover:  # from openstack-cover-jobs template
            timeout: 4800
    gate:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-tempest-with-uwsgi
        - neutron-tempest-linuxbridge
        - neutron-tempest-iptables_hybrid
        - neutron-tempest-multinode-full-py3
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode
        - neutron-tempest-slow-py3
        - neutron-tempest-ipv6-only
        - neutron-ovn-tempest-ovs-release
        - openstack-tox-py36:  # from openstack-python3-victoria-jobs template
            timeout: 3600

    periodic-weekly:
      jobs:
        - neutron-functional
