# NOTE: In doc/source/contributor/testing/ci_scenario_jobs.rst file there is
# document with summary of all tempest, neutron-tempest-plugin and grenade jobs
# summary.
# Please update this document always when any changes to jobs are made.
- project:
    templates:
      - neutron-tempest-plugin-jobs-wallaby
      - openstack-cover-jobs
      - openstack-python3-wallaby-jobs
      - openstack-python3-wallaby-jobs-arm64
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-fullstack-with-uwsgi
        - neutron-rally-task
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode:
            # TODO(slaweq): make that job voting when bug
            # https://bugs.launchpad.net/neutron/+bug/1920778
            # will be fixed
            voting: false
        - neutron-tempest-multinode-full-py3
        - neutron-tempest-dvr-ha-multinode-full
        - neutron-tempest-slow-py3
        - neutron-tempest-ipv6-only
        - neutron-ovn-tempest-ovs-release
        - neutron-ovn-tempest-ovs-release-ipv6-only
        # TODO(slaweq): add this job again to the check queue when it will be
        # working fine on python 3
        #- networking-midonet-tempest-aio-ml2-centos-7:
        #    voting: false
        - neutron-ovn-rally-task:
            voting: false
        # TripleO jobs that deploy OVN.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # In Stein and beyond, fs010 will run using
        # networking-ovn-tripleo-ci-centos-7-containers-multinode.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - openstack-tox-py36:  # from openstack-python3-wallaby-jobs template
            timeout: 3600
        - openstack-tox-py38:  # from openstack-python3-wallaby-jobs template
            timeout: 3600
        - openstack-tox-cover:  # from openstack-cover-jobs template
            timeout: 4800
        - neutron-ovn-tempest-slow
    gate:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-fullstack-with-uwsgi
        - neutron-tempest-multinode-full-py3
        - neutron-grenade-multinode
        # TODO(slaweq): make that job gating when bug
        # https://bugs.launchpad.net/neutron/+bug/1920778
        # will be fixed
        # - neutron-grenade-dvr-multinode
        - neutron-tempest-slow-py3
        - neutron-tempest-ipv6-only
        - neutron-ovn-tempest-ovs-release
        - neutron-ovn-tempest-ovs-release-ipv6-only
        - openstack-tox-py36:  # from openstack-python3-wallaby-jobs template
            timeout: 3600
        - neutron-ovn-tempest-slow
        #- neutron-ovn-rally-task
        #- neutron-ovn-tripleo-ci-centos-8-containers-multinode

    experimental:
      jobs:
        - neutron-grenade-ovn
        - neutron-tempest-with-uwsgi-loki

    periodic:
      jobs:
        - neutron-functional
        - neutron-fullstack
        - neutron-tempest-postgres-full
        - neutron-tempest-mariadb-full
        - devstack-tobiko-faults-centos:
            voting: true
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - openstacksdk-functional-devstack-networking
        - tripleo-ci-centos-8-content-provider
        - neutron-centos-8-tripleo-standalone:
            voting: true
            vars: &consumer_vars
              consumer_job: true
              build_container_images: false
              remove_tags:
                - build
            dependencies: &consumer_deps
              - tripleo-ci-centos-8-content-provider
        - neutron-ovn-tripleo-ci-centos-8-containers-multinode:
            vars: *consumer_vars
            dependencies: *consumer_deps
