- project:
    templates:
      - neutron-tempest-plugin-jobs-2025-2
      - openstack-cover-jobs
      - openstack-python3-jobs
      - openstack-python3-jobs-arm64
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
      - neutron-experimental-jobs
      - neutron-periodic-jobs
      - neutron-tox-override-jobs
      - neutron-skip-level-jobs
    check:
      jobs:
        - neutron-functional
        - neutron-ovs-grenade-multinode
        - neutron-ovn-grenade-multinode
        - neutron-ovs-tempest-multinode-full
        - neutron-ovs-tempest-dvr-ha-multinode-full
        - neutron-ovn-tempest-ipv6-only-ovs-release
        - neutron-ovs-rally-task
        - neutron-ovn-rally-task
        - tempest-integrated-networking:
            irrelevant-files: &ovn-irrelevant-files
              - ^\.pre-commit-config\.yaml$
              - ^\.pylintrc$
              - ^test-requirements.txt$
              - ^releasenotes/.*$
              - ^doc/.*$
              - ^setup.cfg$
              - ^pyproject.toml$
              - ^.*\.conf\.sample$
              - ^.*\.rst$
              - ^neutron/locale/.*$
              - ^neutron/tests/.*$
              - ^tools/.*$
              - ^tox.ini$
              - ^neutron/agent/dhcp/.*$
              - ^neutron/agent/l2/.*$
              - ^neutron/agent/l3/.*$
              - ^neutron/agent/metadata/.*$
              - ^neutron/agent/dhcp_agent.py
              - ^neutron/agent/l3_agent.py
              - ^neutron/agent/metadata_agent.py
              - ^neutron/agent/resource_cache.py
              - ^neutron/agent/rpc.py
              - ^neutron/agent/securitygroup_rpc.py
              - ^neutron/plugins/ml2/drivers/openvswitch/.*$
              - ^neutron/plugins/ml2/drivers/macvtap/.*$
              - ^neutron/plugins/ml2/drivers/mech_sriov/.*$
              - ^neutron/services/qos/drivers/openvswitch/.*$
              - ^neutron/services/trunk/drivers/openvswitch/.*$
              - ^neutron/scheduler/.*$
              - ^roles/.*functional.*$
              - ^playbooks/.*functional.*$
              # Ignore everything except for zuul.d/project.yaml
              - ^zuul.d/base.yaml
              - ^zuul.d/grenade.yaml
              - ^zuul.d/job-templates.yaml
              - ^zuul.d/rally.yaml
              - ^zuul.d/tempest-multinode.yaml
              - ^zuul.d/tempest-singlenode.yaml

    gate:
      jobs:
        - neutron-functional
        - neutron-ovs-tempest-multinode-full
        - neutron-ovn-grenade-multinode
        - neutron-ovs-grenade-multinode
        - neutron-ovn-tempest-ipv6-only-ovs-release
        - tempest-integrated-networking:
            irrelevant-files: *ovn-irrelevant-files
